"""AI/camera simulation endpoints (Phase 10 + YOLO enhancement).

These endpoints make the detector situation explicit:
`GET /api/ai/detector` reports which backends are configured and available,
and `POST /api/ai/simulate-event` generates one clearly-labelled simulated
event. Real YOLO inference lives under /api/ai/detect/*.
"""
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.core.config import settings

from app.ai.detector import get_detector
from app.core.roles import write_access
from app.core.security import get_current_user
from app.database.session import get_db
from app.schemas.camera_event import CameraEventResponse
from app.services.camera_pipeline import generate_simulated_event

router = APIRouter(prefix="/ai", tags=["AI / Camera Simulation"],
                   dependencies=[Depends(get_current_user)])

DbSession = Annotated[Session, Depends(get_db)]


@router.get("/detector")
def detector_info():
    """Active detector backends. Reports REAL YOLO availability honestly:
    'simulated' means no CV model runs; yolo.available means real inference works."""
    simulated = get_detector().health()
    from app.services.yolo_detection import get_yolo_service

    return {
        "configured": settings.AI_DETECTOR,
        "simulated": simulated,
        "yolo": get_yolo_service().model_info(),
    }


@router.post("/simulate-event", response_model=dict, status_code=status.HTTP_201_CREATED)
@router.post("/simulate-event", response_model=dict, status_code=status.HTTP_201_CREATED,
             dependencies=[Depends(write_access("ai_simulation"))])
def simulate_event(
    db: DbSession,
    mine_id: str,
    camera_id: str | None = None,
    zone_id: str | None = None,
):
    """Generate one simulated camera event; returns the event and any alert raised."""
    try:
        event, alert = generate_simulated_event(db, mine_id=mine_id, camera_id=camera_id, zone_id=zone_id)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))
    return {
        "event": CameraEventResponse.model_validate(event),
        "alert": (
            {
                "id": alert.id, "title": alert.title, "severity": alert.severity,
                "source": alert.source, "status": alert.status,
            }
            if alert else None
        ),
        "note": "Event generated by the SIMULATED detector — not real computer vision.",
    }
