"""AI/camera simulation endpoints (Phase 10).

These endpoints make the *simulated* nature of camera events explicit:
`GET /api/ai/detector` reports which detector backend is configured, and
`POST /api/ai/simulate-event` generates one clearly-labelled simulated event.
"""
from typing import Annotated

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.ai.detector import get_detector
from app.core.roles import write_access
from app.core.security import get_current_user
from app.database.session import get_db
from app.schemas.camera_event import CameraEventResponse
from app.services.camera_pipeline import generate_simulated_event

router = APIRouter(prefix="/ai", tags=["AI / Camera Simulation"],
                   dependencies=[Depends(get_current_user)])

DbSession = Annotated[Session, Depends(get_db)]


@router.get("/detector")
def detector_info():
    """Which detector backend is active. 'simulated' means NO real CV model runs."""
    return get_detector().health()


@router.post("/simulate-event", response_model=dict, status_code=status.HTTP_201_CREATED)
@router.post("/simulate-event", response_model=dict, status_code=status.HTTP_201_CREATED,
             dependencies=[Depends(write_access("ai_simulation"))])
def simulate_event(
    db: DbSession,
    mine_id: str,
    camera_id: str | None = None,
    zone_id: str | None = None,
):
    """Generate one simulated camera event; returns the event and any alert raised."""
    try:
        event, alert = generate_simulated_event(db, mine_id=mine_id, camera_id=camera_id, zone_id=zone_id)
    except ValueError as exc:
        raise HTTPException(status_code=status.HTTP_400_BAD_REQUEST, detail=str(exc))
    return {
        "event": CameraEventResponse.model_validate(event),
        "alert": (
            {
                "id": alert.id, "title": alert.title, "severity": alert.severity,
                "source": alert.source, "status": alert.status,
            }
            if alert else None
        ),
        "note": "Event generated by the SIMULATED detector — not real computer vision.",
    }
